spring:
  profiles.active: prd
  datasource:
    url: jdbc:h2:mem:goal-list
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: doc
